from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 524)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.nbr_villes = QtWidgets.QLineEdit(self.centralwidget)
        self.nbr_villes.setEnabled(True)
        self.nbr_villes.setText("")
        self.nbr_villes.setObjectName("nbr_villes")
        self.nbr_villes.setStyleSheet("border: 1px solid black;")
        self.verticalLayout.addWidget(self.nbr_villes)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nbr_population = QtWidgets.QLineEdit(self.centralwidget)
        self.nbr_population.setObjectName("nbr_population")
        self.nbr_population.setStyleSheet("border: 1px solid black;")
        self.horizontalLayout.addWidget(self.nbr_population)
        self.nbr_iterations = QtWidgets.QLineEdit(self.centralwidget)
        self.nbr_iterations.setObjectName("nbr_iterations")
        self.nbr_iterations.setStyleSheet("border: 1px solid black;")
        self.horizontalLayout.addWidget(self.nbr_iterations)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_matrix = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_matrix.setObjectName("pushButton_matrix")
        self.verticalLayout.addWidget(self.pushButton_matrix)
        self.Random_matrix = QtWidgets.QPushButton(self.centralwidget)
        self.Random_matrix.setObjectName("Random_matrix")
        self.verticalLayout.addWidget(self.Random_matrix)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.setStyleSheet("border: 1px solid black;")
        self.verticalLayout.addWidget(self.tableWidget)
        self.auto_complete = QtWidgets.QPushButton(self.centralwidget)
        self.auto_complete.setObjectName("auto_complete")
        self.verticalLayout.addWidget(self.auto_complete)
        self.Get_matrix_content = QtWidgets.QPushButton(self.centralwidget)
        self.Get_matrix_content.setObjectName("Get_matrix_content")
        self.verticalLayout.addWidget(self.Get_matrix_content)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.affichage = QtWidgets.QTextBrowser(self.centralwidget)
        self.affichage.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.affichage.sizePolicy().hasHeightForWidth())
        self.affichage.setSizePolicy(sizePolicy)
        self.affichage.setMaximumSize(QtCore.QSize(16777215, 100))
        self.affichage.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.verticalLayout_2.addWidget(self.affichage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Algorithme Génétique (TSP)"))
        self.nbr_villes.setPlaceholderText(_translate("MainWindow", "Nombre de villes"))
        self.nbr_population.setPlaceholderText(_translate("MainWindow", "Nombre de population"))
        self.nbr_iterations.setPlaceholderText(_translate("MainWindow", "Nombre de generation"))
        self.pushButton_matrix.setText(_translate("MainWindow", "Genéré une matrice vide"))
        self.Random_matrix.setText(_translate("MainWindow", "Genéré une matrice aléatoire"))
        self.auto_complete.setText(_translate("MainWindow", "Remplir le reste de la matrice"))
        self.Get_matrix_content.setText(_translate("MainWindow", "Résoudre"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
